function [t, x] = synthSeedMotion(p)
% SYNTHSEEDMOTION  An exact, prescribed rigid-body seed motion and its 13-state history.
%
% For testing and illustrating the flight-mode metrics and classifiers: every
% motion is built analytically, so its mode is known by construction, with no
% integration and no fitting. Promoted from the local synthMotion in
% testing/shape3d/testPaperMetrics.m (with the 2026-10-03 orbit-sign fix), and
% extended with the options marked NEW for testing/classifier/makeModeExamples.m.
% With the NEW options at their defaults it reproduces the original exactly.
%
% THE MOTION
%   R(t) = Ry_world(phi(t)) * Rx_world(beta(t)) * Rz_body(psi(t))
%     phi   revolution about the world vertical
%     beta  tilt, putting the LONG (span) axis beta degrees below horizontal
%     psi   self-rotation about the body span axis (tumbling / rocking)
%   omega_world = phi' Yhat + beta' (Ry Xhat) + psi' (R zhat), so exactly
%   omega_body  = phi' (R' Yhat) + beta' (R' Ry Xhat) + psi' zhat.
%   CoM: Ry(phi) * [Rh; 0; 0] -- the orbit is generated by the SAME rotation as
%   the attitude, so it turns in the same sense as the body -- plus a descent at
%   V and an optional steady horizontal drift.
%
% INPUT p (struct):
%   .beta        deg, span axis below horizontal (base value)
%   .phiDot      rad/s, revolution about the world vertical
%   .psiDot      rad/s, self-rotation about the span axis
%   .Rh          m, revolution (helix) radius
%   .V           m/s, descent speed
%   .T           s, duration
%   .reversePeriod  s, flip the sign of psiDot every half period   (default 0)
%   .rockAmpDeg, .rockHz   pure rocking of psi instead of psiDot  (default 0)
%   .psi0        NEW deg, constant offset of psi; 90 puts the plate edge-on
%                (normal horizontal)                               (default 0)
%   .vHoriz      NEW 3x1 m/s, steady horizontal drift [X;0;Z] added to the
%                CoM (glides, sideways drift, sliding along the span) (default 0)
%   .betaWobbleDeg, .betaWobbleHz   NEW: beta(t) = beta + A sin(2 pi f t), a
%                wobbling span axis                                (default 0)
%   .chaotic     NEW true -> an attitude that swings widely and never settles,
%                with a drifting descent (the old synthChaotic; uses only .T)
%   .dt          s, sample step                                    (default 1e-3)
%
% OUTPUT
%   t : Nx1 time (s);  x : Nx13 state [r(3) q(4) v(3) omega(3)], world r/v,
%       body omega -- the format ode45 returns for seed6DOFODE / seed6DOFODE3D.

    if ~isfield(p,'reversePeriod'); p.reversePeriod = 0; end
    if ~isfield(p,'rockAmpDeg');    p.rockAmpDeg    = 0; end
    if ~isfield(p,'rockHz');        p.rockHz        = 0; end
    if ~isfield(p,'psi0');          p.psi0          = 0; end
    if ~isfield(p,'vHoriz');        p.vHoriz        = [0;0;0]; end
    if ~isfield(p,'betaWobbleDeg'); p.betaWobbleDeg = 0; end
    if ~isfield(p,'betaWobbleHz');  p.betaWobbleHz  = 0; end
    if ~isfield(p,'chaotic');       p.chaotic       = false; end
    if ~isfield(p,'dt');            p.dt            = 1e-3; end
    if p.chaotic
        [t, x] = chaoticMotion(p.T, p.dt);
        return
    end
    dt = p.dt;   t = (0:dt:p.T).';   n = numel(t);
    vH = p.vHoriz(:);

    % psi(t), reversing or rocking if asked
    if p.rockAmpDeg > 0
        w        = 2*pi*p.rockHz;
        psi      = deg2rad(p.psi0) + deg2rad(p.rockAmpDeg) * sin(w*t);
        psiDot_t = deg2rad(p.rockAmpDeg) * w * cos(w*t);
    elseif p.reversePeriod > 0
        sgn = sign(sin(2*pi*t/p.reversePeriod));  sgn(sgn==0) = 1;
        psiDot_t = p.psiDot * sgn;
        psi = deg2rad(p.psi0) + cumtrapz(t, psiDot_t);
    else
        psiDot_t = p.psiDot * ones(n,1);
        psi = deg2rad(p.psi0) + p.psiDot * t;
    end
    phi = p.phiDot * t;

    % beta(t), wobbling if asked
    wobble = p.betaWobbleDeg > 0;
    if wobble
        wb       = 2*pi*p.betaWobbleHz;
        beta_t   = deg2rad(p.beta + p.betaWobbleDeg * sin(wb*t));
        betaDot  = deg2rad(p.betaWobbleDeg) * wb * cos(wb*t);
    else
        qB = axisAngleToQuat([1;0;0], deg2rad(p.beta));   % fixed tilt, world X
    end

    x = zeros(n, 13);
    for k = 1:n
        qA = axisAngleToQuat([0;1;0], phi(k));          % revolution, world Y
        if wobble;  qB = axisAngleToQuat([1;0;0], beta_t(k));  end
        qC = axisAngleToQuat([0;0;1], psi(k));          % self-rotation, body z
        q  = quatMultiply(quatMultiply(qA, qB), qC);
        R  = quatToRotm(q);
        Ry = quatToRotm(qA);

        omega = p.phiDot * (R.' * [0;1;0]) + psiDot_t(k) * [0;0;1];
        if wobble;  omega = omega + betaDot(k) * (R.' * (Ry * [1;0;0]));  end

        r = Ry * [p.Rh; 0; 0] + [0; -p.V*t(k); 0];
        v = p.phiDot * cross([0;1;0], Ry * [p.Rh; 0; 0]) + [0; -p.V; 0];
        if any(vH);  r = r + vH * t(k);  v = v + vH;  end
        x(k,:) = [r.', q.', v.', omega.'];
    end
end


% =========================================================================
% LOCAL: an attitude that swings widely and never settles (was synthChaotic)
% =========================================================================
function [t, x] = chaoticMotion(T, dt)
    t = (0:dt:T).';  n = numel(t);
    beta = 50*sin(2*pi*t/3.1) + 30*sin(2*pi*t/1.7 + 1.0);      % deg, wild swing
    phi  = 0.8*sin(2*pi*t/5.3);
    V    = 2.0 + 1.5*t/T;                                       % never settles
    x = zeros(n,13);
    for k = 1:n
        qA = axisAngleToQuat([0;1;0], phi(k));
        qB = axisAngleToQuat([1;0;0], deg2rad(beta(k)));
        q  = quatMultiply(qA, qB);
        if k < 2; y = 0; else; y = trapz(t(1:k), V(1:k)); end
        x(k,:) = [0.01*sin(t(k)), -y, 0.01*cos(t(k)), q.', 0, -V(k), 0, 0, 0, 0];
    end
    % body angular velocity by finite difference of the quaternion (adequate:
    % this case only has to be incoherent, not exact)
    for k = 2:n-1
        R1 = quatToRotm(x(k-1,4:7).');  R2 = quatToRotm(x(k+1,4:7).');
        W  = R1.' * (R2 - R1) / (2*dt);
        x(k,11:13) = [W(3,2), W(1,3), W(2,1)];
    end
end
